apiVersion: apps/v1
kind: Deployment
metadata:
  name: handler
  labels:
    app: handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handler
  template:
    metadata:
      labels:
        app: handler
    spec:
      containers:
      - name: handler
        image: docker.io/rxdperez/testrepo:handlerv1
        ports:
        - containerPort: 8085
